# -*- coding: utf-8 -*-
"""2020-10-04-item-based-CF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQXdGFtPqRCdkWLNaEQJsmFOmltXNTMn
"""

import zipfile
from google.colab import drive

# 구글 드라이브 마운트
drive.mount('/content/drive/')

# Kaggle MovieLens zip 파일로 업로드
zip_ref = zipfile.ZipFile("/content/drive/My Drive/Colab Notebooks/data/movieLens.zip", 'r')

# zip 파일 저장
zip_ref.extractall("/tmp")
zip_ref.close()

# zip 파일 내 목록 확인
import os
arr = os.listdir('/tmp')
print(arr)

import pandas as pd
# rating 데이터
rating = pd.read_csv('/tmp/rating.csv')
rating.drop('timestamp', axis=1, inplace=True)
rating.head()

# movie 데이터
movie = pd.read_csv('/tmp/movie.csv')
movie.head()

user_movie_rating = pd.merge(rating, movie, on='movieId')
user_movie_rating.head()

# 데이터가 커서 절반만
user_movie_rating = user_movie_rating[:len(user_movie_rating)//2]

movie_user_rating = user_movie_rating.pivot_table(values='rating', index='title', columns='userId').fillna(0)
movie_user_rating.head()

user_movie_rating = user_movie_rating.pivot_table(values='rating', index='userId', columns='title').fillna(0)
user_movie_rating.head()

from sklearn.metrics.pairwise import cosine_similarity
item_based_collabor = cosine_similarity(movie_user_rating)
item_based_collabor

item_based_collabor = pd.DataFrame(data=item_based_collabor, index=movie_user_rating.index, columns=movie_user_rating.index)
item_based_collabor.head()

def get_item_based_collabor(title):
    return item_based_collabor[title].sort_values(ascending=False)[:6]  
get_item_based_collabor('Godfather, The (1972)')